### ISSUE TITLE
New Test - data-unencrypted-internal/android-data-in-sandbox/test.md

### ISSUE THREAD

**Issue by thomascannon** [OWASP/mastg#2567]
Add an example test implementation for `risks/MASVS-STORAGE/1-store-sensitive-data-securely/data-unencrypted-internal/android-data-in-sandbox/test.md` (once merged by PR #2566)

Location should be `risks/MASVS-STORAGE/1-store-sensitive-data-securely/data-unencrypted-internal/android-data-in-sandbox/example-1/example.md`

**Comment by cpholguera** [comment]
Demo will be added in https://github.com/OWASP/owasp-mastg/issues/2544
